<?php
$data = array (
  290 => 
  array (
    'cat_id' => '290',
    'cat_name' => '米面粮油',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '4',
    'sort_order' => '10',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '290',
    'name' => '米面粮油',
  ),
  293 => 
  array (
    'cat_id' => '293',
    'cat_name' => '大米',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
    'level' => 1,
    'id' => '293',
    'name' => '大米',
  ),
  295 => 
  array (
    'cat_id' => '295',
    'cat_name' => '杂粮',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '295',
    'name' => '杂粮',
  ),
  294 => 
  array (
    'cat_id' => '294',
    'cat_name' => '面粉',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '294',
    'name' => '面粉',
  ),
  255 => 
  array (
    'cat_id' => '255',
    'cat_name' => '南北干货',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '255',
    'name' => '南北干货',
  ),
  252 => 
  array (
    'cat_id' => '252',
    'cat_name' => '调味品',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '2',
    'level' => 1,
    'id' => '252',
    'name' => '调味品',
  ),
  303 => 
  array (
    'cat_id' => '303',
    'cat_name' => '即食汤料',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '303',
    'name' => '即食汤料',
  ),
  300 => 
  array (
    'cat_id' => '300',
    'cat_name' => '盐',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '300',
    'name' => '盐',
  ),
  304 => 
  array (
    'cat_id' => '304',
    'cat_name' => '腌制品',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '304',
    'name' => '腌制品',
  ),
  301 => 
  array (
    'cat_id' => '301',
    'cat_name' => '糖',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '301',
    'name' => '糖',
  ),
  297 => 
  array (
    'cat_id' => '297',
    'cat_name' => '调味料',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '297',
    'name' => '调味料',
  ),
  299 => 
  array (
    'cat_id' => '299',
    'cat_name' => '酱油',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '299',
    'name' => '酱油',
  ),
  298 => 
  array (
    'cat_id' => '298',
    'cat_name' => '调味酱',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '298',
    'name' => '调味酱',
  ),
  302 => 
  array (
    'cat_id' => '302',
    'cat_name' => '醋',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '302',
    'name' => '醋',
  ),
  296 => 
  array (
    'cat_id' => '296',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '296',
    'name' => '食用油',
  ),
  286 => 
  array (
    'cat_id' => '286',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '286',
    'name' => '方便速食',
  ),
  291 => 
  array (
    'cat_id' => '291',
    'cat_name' => '北大荒系列',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '291',
    'name' => '北大荒系列',
  ),
  247 => 
  array (
    'cat_id' => '247',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '247',
    'name' => '休闲食品',
  ),
  254 => 
  array (
    'cat_id' => '254',
    'cat_name' => '糖果巧克力',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '254',
    'name' => '糖果巧克力',
  ),
  378 => 
  array (
    'cat_id' => '378',
    'cat_name' => '润喉糖',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '378',
    'name' => '润喉糖',
  ),
  379 => 
  array (
    'cat_id' => '379',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '379',
    'name' => '糖果',
  ),
  370 => 
  array (
    'cat_id' => '370',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '370',
    'name' => '巧克力',
  ),
  377 => 
  array (
    'cat_id' => '377',
    'cat_name' => '口香糖',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '377',
    'name' => '口香糖',
  ),
  251 => 
  array (
    'cat_id' => '251',
    'cat_name' => '饼干糕点',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '251',
    'name' => '饼干糕点',
  ),
  322 => 
  array (
    'cat_id' => '322',
    'cat_name' => '沙琪玛',
    'measure_unit' => '',
    'parent_id' => '251',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '322',
    'name' => '沙琪玛',
  ),
  319 => 
  array (
    'cat_id' => '319',
    'cat_name' => '蛋糕/派',
    'measure_unit' => '',
    'parent_id' => '251',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '319',
    'name' => '蛋糕/派',
  ),
  320 => 
  array (
    'cat_id' => '320',
    'cat_name' => '威化',
    'measure_unit' => '',
    'parent_id' => '251',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '320',
    'name' => '威化',
  ),
  321 => 
  array (
    'cat_id' => '321',
    'cat_name' => '饼干',
    'measure_unit' => '',
    'parent_id' => '251',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '321',
    'name' => '饼干',
  ),
  249 => 
  array (
    'cat_id' => '249',
    'cat_name' => '休闲零食',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '249',
    'name' => '休闲零食',
  ),
  316 => 
  array (
    'cat_id' => '316',
    'cat_name' => '膨化',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '316',
    'name' => '膨化',
  ),
  313 => 
  array (
    'cat_id' => '313',
    'cat_name' => '果冻',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '313',
    'name' => '果冻',
  ),
  310 => 
  array (
    'cat_id' => '310',
    'cat_name' => '薯片',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '310',
    'name' => '薯片',
  ),
  317 => 
  array (
    'cat_id' => '317',
    'cat_name' => '海苔',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '317',
    'name' => '海苔',
  ),
  314 => 
  array (
    'cat_id' => '314',
    'cat_name' => '爆米花',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '314',
    'name' => '爆米花',
  ),
  311 => 
  array (
    'cat_id' => '311',
    'cat_name' => '坚果',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '311',
    'name' => '坚果',
  ),
  318 => 
  array (
    'cat_id' => '318',
    'cat_name' => '肉松',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '318',
    'name' => '肉松',
  ),
  315 => 
  array (
    'cat_id' => '315',
    'cat_name' => '红枣',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '315',
    'name' => '红枣',
  ),
  312 => 
  array (
    'cat_id' => '312',
    'cat_name' => '肉干',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '312',
    'name' => '肉干',
  ),
  256 => 
  array (
    'cat_id' => '256',
    'cat_name' => '地方特产',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '256',
    'name' => '地方特产',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '冲调饮品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '冲调饮品',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '有机茶',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '28',
    'name' => '有机茶',
  ),
  287 => 
  array (
    'cat_id' => '287',
    'cat_name' => '酒水饮料',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '287',
    'name' => '酒水饮料',
  ),
  332 => 
  array (
    'cat_id' => '332',
    'cat_name' => '功能饮料',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '332',
    'name' => '功能饮料',
  ),
  329 => 
  array (
    'cat_id' => '329',
    'cat_name' => '咖啡饮料',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '329',
    'name' => '咖啡饮料',
  ),
  323 => 
  array (
    'cat_id' => '323',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '323',
    'name' => '白酒',
  ),
  330 => 
  array (
    'cat_id' => '330',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '330',
    'name' => '碳酸饮料',
  ),
  324 => 
  array (
    'cat_id' => '324',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '324',
    'name' => '葡萄酒',
  ),
  331 => 
  array (
    'cat_id' => '331',
    'cat_name' => '茶饮料',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '331',
    'name' => '茶饮料',
  ),
  328 => 
  array (
    'cat_id' => '328',
    'cat_name' => '果汁',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '328',
    'name' => '果汁',
  ),
  325 => 
  array (
    'cat_id' => '325',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '325',
    'name' => '啤酒',
  ),
  343 => 
  array (
    'cat_id' => '343',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
    'level' => 1,
    'id' => '343',
    'name' => '茶叶',
  ),
  285 => 
  array (
    'cat_id' => '285',
    'cat_name' => '果蔬籽粉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '285',
    'name' => '果蔬籽粉',
  ),
  253 => 
  array (
    'cat_id' => '253',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '253',
    'name' => '蜂蜜',
  ),
  250 => 
  array (
    'cat_id' => '250',
    'cat_name' => '豆奶豆乳',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '250',
    'name' => '豆奶豆乳',
  ),
  257 => 
  array (
    'cat_id' => '257',
    'cat_name' => '进口食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '257',
    'name' => '进口食品',
  ),
  261 => 
  array (
    'cat_id' => '261',
    'cat_name' => '糖果巧克力',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '261',
    'name' => '糖果巧克力',
  ),
  262 => 
  array (
    'cat_id' => '262',
    'cat_name' => '进口酒',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '262',
    'name' => '进口酒',
  ),
  259 => 
  array (
    'cat_id' => '259',
    'cat_name' => '进口咖啡茶叶',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '259',
    'name' => '进口咖啡茶叶',
  ),
  389 => 
  array (
    'cat_id' => '389',
    'cat_name' => '进口牛奶',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '389',
    'name' => '进口牛奶',
  ),
  260 => 
  array (
    'cat_id' => '260',
    'cat_name' => '进口果汁',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '260',
    'name' => '进口果汁',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '台湾食品',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '95',
    'has_children' => '0',
    'goods_num' => '27',
    'level' => 1,
    'id' => '9',
    'name' => '台湾食品',
  ),
  292 => 
  array (
    'cat_id' => '292',
    'cat_name' => '果蔬生鲜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '16',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '292',
    'name' => '果蔬生鲜',
  ),
  386 => 
  array (
    'cat_id' => '386',
    'cat_name' => '金枪鱼',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '386',
    'name' => '金枪鱼',
  ),
  243 => 
  array (
    'cat_id' => '243',
    'cat_name' => '鲜肉禽蛋',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 1,
    'id' => '243',
    'name' => '鲜肉禽蛋',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => '蔬菜水果',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => '25',
    'level' => 1,
    'id' => '245',
    'name' => '蔬菜水果',
  ),
  272 => 
  array (
    'cat_id' => '272',
    'cat_name' => '生活家居',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '17',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '272',
    'name' => '生活家居',
  ),
  274 => 
  array (
    'cat_id' => '274',
    'cat_name' => '收纳洗晒',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '274',
    'name' => '收纳洗晒',
  ),
  352 => 
  array (
    'cat_id' => '352',
    'cat_name' => '粘钩/挂钩',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '352',
    'name' => '粘钩/挂钩',
  ),
  349 => 
  array (
    'cat_id' => '349',
    'cat_name' => '衣架',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '349',
    'name' => '衣架',
  ),
  350 => 
  array (
    'cat_id' => '350',
    'cat_name' => '收纳箱/袋/盒',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '350',
    'name' => '收纳箱/袋/盒',
  ),
  351 => 
  array (
    'cat_id' => '351',
    'cat_name' => '洗衣栏/收纳篮',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '351',
    'name' => '洗衣栏/收纳篮',
  ),
  275 => 
  array (
    'cat_id' => '275',
    'cat_name' => '家纺日用品',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '275',
    'name' => '家纺日用品',
  ),
  359 => 
  array (
    'cat_id' => '359',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '359',
    'name' => '拖鞋',
  ),
  356 => 
  array (
    'cat_id' => '356',
    'cat_name' => '墙贴',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '356',
    'name' => '墙贴',
  ),
  357 => 
  array (
    'cat_id' => '357',
    'cat_name' => '钟表',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '357',
    'name' => '钟表',
  ),
  348 => 
  array (
    'cat_id' => '348',
    'cat_name' => '毛巾浴巾',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '348',
    'name' => '毛巾浴巾',
  ),
  358 => 
  array (
    'cat_id' => '358',
    'cat_name' => '雨伞',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '358',
    'name' => '雨伞',
  ),
  276 => 
  array (
    'cat_id' => '276',
    'cat_name' => '餐具餐饰',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '276',
    'name' => '餐具餐饰',
  ),
  355 => 
  array (
    'cat_id' => '355',
    'cat_name' => '刀/叉/汤匙',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '355',
    'name' => '刀/叉/汤匙',
  ),
  353 => 
  array (
    'cat_id' => '353',
    'cat_name' => '桌布台布',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '353',
    'name' => '桌布台布',
  ),
  369 => 
  array (
    'cat_id' => '369',
    'cat_name' => '保鲜盒/饭盒',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '369',
    'name' => '保鲜盒/饭盒',
  ),
  354 => 
  array (
    'cat_id' => '354',
    'cat_name' => '碗碟盘筷',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '354',
    'name' => '碗碟盘筷',
  ),
  273 => 
  array (
    'cat_id' => '273',
    'cat_name' => '床上用品',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '273',
    'name' => '床上用品',
  ),
  346 => 
  array (
    'cat_id' => '346',
    'cat_name' => '被罩床单',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '346',
    'name' => '被罩床单',
  ),
  347 => 
  array (
    'cat_id' => '347',
    'cat_name' => '凉席凉枕',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '347',
    'name' => '凉席凉枕',
  ),
  344 => 
  array (
    'cat_id' => '344',
    'cat_name' => '被子枕头',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '344',
    'name' => '被子枕头',
  ),
  289 => 
  array (
    'cat_id' => '289',
    'cat_name' => '童车童床',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '289',
    'name' => '童车童床',
  ),
  368 => 
  array (
    'cat_id' => '368',
    'cat_name' => '儿童床/桌椅',
    'measure_unit' => '',
    'parent_id' => '289',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '368',
    'name' => '儿童床/桌椅',
  ),
  365 => 
  array (
    'cat_id' => '365',
    'cat_name' => '婴儿推车',
    'measure_unit' => '',
    'parent_id' => '289',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '365',
    'name' => '婴儿推车',
  ),
  366 => 
  array (
    'cat_id' => '366',
    'cat_name' => '儿童自行车',
    'measure_unit' => '',
    'parent_id' => '289',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '366',
    'name' => '儿童自行车',
  ),
  367 => 
  array (
    'cat_id' => '367',
    'cat_name' => '汽车安全座椅',
    'measure_unit' => '',
    'parent_id' => '289',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '367',
    'name' => '汽车安全座椅',
  ),
  306 => 
  array (
    'cat_id' => '306',
    'cat_name' => '清洁用品',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '306',
    'name' => '清洁用品',
  ),
  362 => 
  array (
    'cat_id' => '362',
    'cat_name' => '洗衣液',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '362',
    'name' => '洗衣液',
  ),
  336 => 
  array (
    'cat_id' => '336',
    'cat_name' => '洗衣粉',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '336',
    'name' => '洗衣粉',
  ),
  363 => 
  array (
    'cat_id' => '363',
    'cat_name' => '空气清新剂',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '363',
    'name' => '空气清新剂',
  ),
  360 => 
  array (
    'cat_id' => '360',
    'cat_name' => '洗衣皂',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '360',
    'name' => '洗衣皂',
  ),
  337 => 
  array (
    'cat_id' => '337',
    'cat_name' => '洗洁精',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '337',
    'name' => '洗洁精',
  ),
  364 => 
  array (
    'cat_id' => '364',
    'cat_name' => '家居清洁剂',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '364',
    'name' => '家居清洁剂',
  ),
  361 => 
  array (
    'cat_id' => '361',
    'cat_name' => '消毒除菌',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '361',
    'name' => '消毒除菌',
  ),
  385 => 
  array (
    'cat_id' => '385',
    'cat_name' => '干果山珍',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '17',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '385',
    'name' => '干果山珍',
  ),
  387 => 
  array (
    'cat_id' => '387',
    'cat_name' => '干果坚果',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
    'level' => 1,
    'id' => '387',
    'name' => '干果坚果',
  ),
  388 => 
  array (
    'cat_id' => '388',
    'cat_name' => '山珍山货',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '33',
    'level' => 1,
    'id' => '388',
    'name' => '山珍山货',
  ),
  284 => 
  array (
    'cat_id' => '284',
    'cat_name' => '礼品卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '18',
    'has_children' => '2',
    'goods_num' => '3',
    'level' => 0,
    'id' => '284',
    'name' => '礼品卡',
  ),
  371 => 
  array (
    'cat_id' => '371',
    'cat_name' => '一卡换多卡',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '35',
    'level' => 1,
    'id' => '371',
    'name' => '一卡换多卡',
  ),
  372 => 
  array (
    'cat_id' => '372',
    'cat_name' => '礼卡充值',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '372',
    'name' => '礼卡充值',
  ),
  264 => 
  array (
    'cat_id' => '264',
    'cat_name' => '母婴用品玩具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '264',
    'name' => '母婴用品玩具',
  ),
  265 => 
  array (
    'cat_id' => '265',
    'cat_name' => '宝宝吃什么',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '265',
    'name' => '宝宝吃什么',
  ),
  266 => 
  array (
    'cat_id' => '266',
    'cat_name' => '玩具文教',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '266',
    'name' => '玩具文教',
  ),
  277 => 
  array (
    'cat_id' => '277',
    'cat_name' => '营养保健维生素钙剂',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '277',
    'name' => '营养保健维生素钙剂',
  ),
  280 => 
  array (
    'cat_id' => '280',
    'cat_name' => '中老年保健',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '280',
    'name' => '中老年保健',
  ),
  281 => 
  array (
    'cat_id' => '281',
    'cat_name' => '儿童保健',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '281',
    'name' => '儿童保健',
  ),
  278 => 
  array (
    'cat_id' => '278',
    'cat_name' => '增强免疫',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '278',
    'name' => '增强免疫',
  ),
  282 => 
  array (
    'cat_id' => '282',
    'cat_name' => '维生素钙',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '282',
    'name' => '维生素钙',
  ),
  279 => 
  array (
    'cat_id' => '279',
    'cat_name' => '美容养颜',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '279',
    'name' => '美容养颜',
  ),
  283 => 
  array (
    'cat_id' => '283',
    'cat_name' => '瘦身美体',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '283',
    'name' => '瘦身美体',
  ),
  248 => 
  array (
    'cat_id' => '248',
    'cat_name' => '',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '248',
    'name' => '',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '米面',
    'measure_unit' => '袋',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '米面',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '米面杂粮',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '12',
    'name' => '米面杂粮',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '食用油',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '南北干货',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '南北干货',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '有机食品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '有机食品',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '调味品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '调味品',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '速食',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '速食',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '其他分类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '18',
    'goods_num' => '2',
    'level' => 0,
    'id' => '39',
    'name' => '其他分类',
  ),
  338 => 
  array (
    'cat_id' => '338',
    'cat_name' => '奶粉',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '338',
    'name' => '奶粉',
  ),
  335 => 
  array (
    'cat_id' => '335',
    'cat_name' => '豆奶',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '335',
    'name' => '豆奶',
  ),
  381 => 
  array (
    'cat_id' => '381',
    'cat_name' => '芝麻糊',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '381',
    'name' => '芝麻糊',
  ),
  342 => 
  array (
    'cat_id' => '342',
    'cat_name' => '咖啡伴侣',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '342',
    'name' => '咖啡伴侣',
  ),
  375 => 
  array (
    'cat_id' => '375',
    'cat_name' => '月饼卷',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '375',
    'name' => '月饼卷',
  ),
  326 => 
  array (
    'cat_id' => '326',
    'cat_name' => '果蔬籽粉',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '326',
    'name' => '果蔬籽粉',
  ),
  339 => 
  array (
    'cat_id' => '339',
    'cat_name' => '口味奶',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '339',
    'name' => '口味奶',
  ),
  382 => 
  array (
    'cat_id' => '382',
    'cat_name' => '藕粉',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '382',
    'name' => '藕粉',
  ),
  333 => 
  array (
    'cat_id' => '333',
    'cat_name' => '纯牛奶',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '333',
    'name' => '纯牛奶',
  ),
  376 => 
  array (
    'cat_id' => '376',
    'cat_name' => '果蔬卡',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '376',
    'name' => '果蔬卡',
  ),
  327 => 
  array (
    'cat_id' => '327',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '327',
    'name' => '蜂蜜',
  ),
  373 => 
  array (
    'cat_id' => '373',
    'cat_name' => '冰淇淋/面包',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '373',
    'name' => '冰淇淋/面包',
  ),
  340 => 
  array (
    'cat_id' => '340',
    'cat_name' => '速溶咖啡',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '340',
    'name' => '速溶咖啡',
  ),
  383 => 
  array (
    'cat_id' => '383',
    'cat_name' => '奶茶/柚子茶',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '383',
    'name' => '奶茶/柚子茶',
  ),
  334 => 
  array (
    'cat_id' => '334',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '334',
    'name' => '酸奶',
  ),
  380 => 
  array (
    'cat_id' => '380',
    'cat_name' => '果汁冲饮',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '380',
    'name' => '果汁冲饮',
  ),
  374 => 
  array (
    'cat_id' => '374',
    'cat_name' => '大闸蟹卷',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '374',
    'name' => '大闸蟹卷',
  ),
  341 => 
  array (
    'cat_id' => '341',
    'cat_name' => '咖啡豆粉',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '341',
    'name' => '咖啡豆粉',
  ),
  267 => 
  array (
    'cat_id' => '267',
    'cat_name' => '厨房用品清洁用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '267',
    'name' => '厨房用品清洁用品',
  ),
  271 => 
  array (
    'cat_id' => '271',
    'cat_name' => '清洁用具',
    'measure_unit' => '',
    'parent_id' => '267',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '271',
    'name' => '清洁用具',
  ),
  268 => 
  array (
    'cat_id' => '268',
    'cat_name' => '锅具水壶',
    'measure_unit' => '',
    'parent_id' => '267',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '268',
    'name' => '锅具水壶',
  ),
  269 => 
  array (
    'cat_id' => '269',
    'cat_name' => '纸制品',
    'measure_unit' => '',
    'parent_id' => '267',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '269',
    'name' => '纸制品',
  ),
  270 => 
  array (
    'cat_id' => '270',
    'cat_name' => '清洁剂',
    'measure_unit' => '',
    'parent_id' => '267',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '270',
    'name' => '清洁剂',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '3',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '3',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '酒水',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => '酒水',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '地方特色茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '地方特色茶',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '中粮茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '中粮茶',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '健康食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '90',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '8',
    'name' => '健康食品',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '营养健康',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '23',
    'name' => '营养健康',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '坚果系列',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '坚果系列',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '刺五加系列',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '35',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '刺五加系列',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '营养滋补',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => '营养滋补',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '江中参灵草',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => '23',
    'level' => 1,
    'id' => '24',
    'name' => '江中参灵草',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => '粽香情浓',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '244',
    'name' => '粽香情浓',
  ),
);
?>