<?php
$data = array (
  0 => 
  array (
    'cat_id' => '290',
    'cat_name' => '米面粮油',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '4',
    'sort_order' => '10',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '247',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '6',
    'cat_name' => '冲调饮品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '257',
    'cat_name' => '进口食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '292',
    'cat_name' => '果蔬生鲜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '16',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '272',
    'cat_name' => '生活家居',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '17',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '385',
    'cat_name' => '干果山珍',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '17',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '284',
    'cat_name' => '礼品卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '18',
    'has_children' => '2',
    'goods_num' => '3',
  ),
  8 => 
  array (
    'cat_id' => '264',
    'cat_name' => '母婴用品玩具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '277',
    'cat_name' => '营养保健维生素钙剂',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '248',
    'cat_name' => '',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '5',
    'cat_name' => '米面',
    'measure_unit' => '袋',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '39',
    'cat_name' => '其他分类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '18',
    'goods_num' => '2',
  ),
  13 => 
  array (
    'cat_id' => '267',
    'cat_name' => '厨房用品清洁用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '7',
    'cat_name' => '3',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '8',
    'cat_name' => '健康食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '90',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '244',
    'cat_name' => '粽香情浓',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '12',
    'cat_name' => '米面杂粮',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '13',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '15',
    'cat_name' => '南北干货',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '14',
    'cat_name' => '有机食品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '16',
    'cat_name' => '调味品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '11',
    'cat_name' => '速食',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '28',
    'cat_name' => '有机茶',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  24 => 
  array (
    'cat_id' => '287',
    'cat_name' => '酒水饮料',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '343',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
  ),
  26 => 
  array (
    'cat_id' => '285',
    'cat_name' => '果蔬籽粉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  27 => 
  array (
    'cat_id' => '253',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
  ),
  28 => 
  array (
    'cat_id' => '250',
    'cat_name' => '豆奶豆乳',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  29 => 
  array (
    'cat_id' => '27',
    'cat_name' => '酒水',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '36',
    'cat_name' => '地方特色茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '38',
    'cat_name' => '中粮茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '23',
    'cat_name' => '营养健康',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  33 => 
  array (
    'cat_id' => '22',
    'cat_name' => '坚果系列',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '26',
    'cat_name' => '刺五加系列',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '35',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '25',
    'cat_name' => '营养滋补',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '24',
    'cat_name' => '江中参灵草',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => '23',
  ),
  37 => 
  array (
    'cat_id' => '338',
    'cat_name' => '奶粉',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '335',
    'cat_name' => '豆奶',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '381',
    'cat_name' => '芝麻糊',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '342',
    'cat_name' => '咖啡伴侣',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '375',
    'cat_name' => '月饼卷',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '326',
    'cat_name' => '果蔬籽粉',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '339',
    'cat_name' => '口味奶',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '382',
    'cat_name' => '藕粉',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '333',
    'cat_name' => '纯牛奶',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '376',
    'cat_name' => '果蔬卡',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '327',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '373',
    'cat_name' => '冰淇淋/面包',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '340',
    'cat_name' => '速溶咖啡',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '383',
    'cat_name' => '奶茶/柚子茶',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '334',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '380',
    'cat_name' => '果汁冲饮',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '374',
    'cat_name' => '大闸蟹卷',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '341',
    'cat_name' => '咖啡豆粉',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '254',
    'cat_name' => '糖果巧克力',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '251',
    'cat_name' => '饼干糕点',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '249',
    'cat_name' => '休闲零食',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '256',
    'cat_name' => '地方特产',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '316',
    'cat_name' => '膨化',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '313',
    'cat_name' => '果冻',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '310',
    'cat_name' => '薯片',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '317',
    'cat_name' => '海苔',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '314',
    'cat_name' => '爆米花',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '311',
    'cat_name' => '坚果',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  65 => 
  array (
    'cat_id' => '318',
    'cat_name' => '肉松',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '315',
    'cat_name' => '红枣',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '312',
    'cat_name' => '肉干',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '322',
    'cat_name' => '沙琪玛',
    'measure_unit' => '',
    'parent_id' => '251',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '319',
    'cat_name' => '蛋糕/派',
    'measure_unit' => '',
    'parent_id' => '251',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '320',
    'cat_name' => '威化',
    'measure_unit' => '',
    'parent_id' => '251',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '321',
    'cat_name' => '饼干',
    'measure_unit' => '',
    'parent_id' => '251',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '303',
    'cat_name' => '即食汤料',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '300',
    'cat_name' => '盐',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '304',
    'cat_name' => '腌制品',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '301',
    'cat_name' => '糖',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '297',
    'cat_name' => '调味料',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '299',
    'cat_name' => '酱油',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '298',
    'cat_name' => '调味酱',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '302',
    'cat_name' => '醋',
    'measure_unit' => '',
    'parent_id' => '252',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '378',
    'cat_name' => '润喉糖',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '379',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '370',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '377',
    'cat_name' => '口香糖',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  84 => 
  array (
    'cat_id' => '261',
    'cat_name' => '糖果巧克力',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  85 => 
  array (
    'cat_id' => '262',
    'cat_name' => '进口酒',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '259',
    'cat_name' => '进口咖啡茶叶',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '389',
    'cat_name' => '进口牛奶',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  88 => 
  array (
    'cat_id' => '260',
    'cat_name' => '进口果汁',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  89 => 
  array (
    'cat_id' => '9',
    'cat_name' => '台湾食品',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '95',
    'has_children' => '0',
    'goods_num' => '27',
  ),
  90 => 
  array (
    'cat_id' => '265',
    'cat_name' => '宝宝吃什么',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '266',
    'cat_name' => '玩具文教',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  92 => 
  array (
    'cat_id' => '271',
    'cat_name' => '清洁用具',
    'measure_unit' => '',
    'parent_id' => '267',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '268',
    'cat_name' => '锅具水壶',
    'measure_unit' => '',
    'parent_id' => '267',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  94 => 
  array (
    'cat_id' => '269',
    'cat_name' => '纸制品',
    'measure_unit' => '',
    'parent_id' => '267',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '270',
    'cat_name' => '清洁剂',
    'measure_unit' => '',
    'parent_id' => '267',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  96 => 
  array (
    'cat_id' => '274',
    'cat_name' => '收纳洗晒',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  97 => 
  array (
    'cat_id' => '275',
    'cat_name' => '家纺日用品',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '276',
    'cat_name' => '餐具餐饰',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '273',
    'cat_name' => '床上用品',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '289',
    'cat_name' => '童车童床',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '306',
    'cat_name' => '清洁用品',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '346',
    'cat_name' => '被罩床单',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '347',
    'cat_name' => '凉席凉枕',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '344',
    'cat_name' => '被子枕头',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  105 => 
  array (
    'cat_id' => '352',
    'cat_name' => '粘钩/挂钩',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '349',
    'cat_name' => '衣架',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '350',
    'cat_name' => '收纳箱/袋/盒',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  108 => 
  array (
    'cat_id' => '351',
    'cat_name' => '洗衣栏/收纳篮',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  109 => 
  array (
    'cat_id' => '359',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  110 => 
  array (
    'cat_id' => '356',
    'cat_name' => '墙贴',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  111 => 
  array (
    'cat_id' => '357',
    'cat_name' => '钟表',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  112 => 
  array (
    'cat_id' => '348',
    'cat_name' => '毛巾浴巾',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  113 => 
  array (
    'cat_id' => '358',
    'cat_name' => '雨伞',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  114 => 
  array (
    'cat_id' => '355',
    'cat_name' => '刀/叉/汤匙',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  115 => 
  array (
    'cat_id' => '353',
    'cat_name' => '桌布台布',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  116 => 
  array (
    'cat_id' => '369',
    'cat_name' => '保鲜盒/饭盒',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  117 => 
  array (
    'cat_id' => '354',
    'cat_name' => '碗碟盘筷',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '280',
    'cat_name' => '中老年保健',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  119 => 
  array (
    'cat_id' => '281',
    'cat_name' => '儿童保健',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  120 => 
  array (
    'cat_id' => '278',
    'cat_name' => '增强免疫',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  121 => 
  array (
    'cat_id' => '282',
    'cat_name' => '维生素钙',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  122 => 
  array (
    'cat_id' => '279',
    'cat_name' => '美容养颜',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  123 => 
  array (
    'cat_id' => '283',
    'cat_name' => '瘦身美体',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  124 => 
  array (
    'cat_id' => '371',
    'cat_name' => '一卡换多卡',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '35',
  ),
  125 => 
  array (
    'cat_id' => '372',
    'cat_name' => '礼卡充值',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  126 => 
  array (
    'cat_id' => '332',
    'cat_name' => '功能饮料',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  127 => 
  array (
    'cat_id' => '329',
    'cat_name' => '咖啡饮料',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '323',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  129 => 
  array (
    'cat_id' => '330',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  130 => 
  array (
    'cat_id' => '324',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  131 => 
  array (
    'cat_id' => '331',
    'cat_name' => '茶饮料',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  132 => 
  array (
    'cat_id' => '328',
    'cat_name' => '果汁',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  133 => 
  array (
    'cat_id' => '325',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  134 => 
  array (
    'cat_id' => '368',
    'cat_name' => '儿童床/桌椅',
    'measure_unit' => '',
    'parent_id' => '289',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  135 => 
  array (
    'cat_id' => '365',
    'cat_name' => '婴儿推车',
    'measure_unit' => '',
    'parent_id' => '289',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  136 => 
  array (
    'cat_id' => '366',
    'cat_name' => '儿童自行车',
    'measure_unit' => '',
    'parent_id' => '289',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  137 => 
  array (
    'cat_id' => '367',
    'cat_name' => '汽车安全座椅',
    'measure_unit' => '',
    'parent_id' => '289',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  138 => 
  array (
    'cat_id' => '293',
    'cat_name' => '大米',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
  ),
  139 => 
  array (
    'cat_id' => '295',
    'cat_name' => '杂粮',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  140 => 
  array (
    'cat_id' => '294',
    'cat_name' => '面粉',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  141 => 
  array (
    'cat_id' => '255',
    'cat_name' => '南北干货',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  142 => 
  array (
    'cat_id' => '252',
    'cat_name' => '调味品',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '2',
  ),
  143 => 
  array (
    'cat_id' => '296',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  144 => 
  array (
    'cat_id' => '286',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  145 => 
  array (
    'cat_id' => '291',
    'cat_name' => '北大荒系列',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  146 => 
  array (
    'cat_id' => '386',
    'cat_name' => '金枪鱼',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  147 => 
  array (
    'cat_id' => '243',
    'cat_name' => '鲜肉禽蛋',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => '17',
  ),
  148 => 
  array (
    'cat_id' => '245',
    'cat_name' => '蔬菜水果',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => '25',
  ),
  149 => 
  array (
    'cat_id' => '362',
    'cat_name' => '洗衣液',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  150 => 
  array (
    'cat_id' => '336',
    'cat_name' => '洗衣粉',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  151 => 
  array (
    'cat_id' => '363',
    'cat_name' => '空气清新剂',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  152 => 
  array (
    'cat_id' => '360',
    'cat_name' => '洗衣皂',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  153 => 
  array (
    'cat_id' => '337',
    'cat_name' => '洗洁精',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  154 => 
  array (
    'cat_id' => '364',
    'cat_name' => '家居清洁剂',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  155 => 
  array (
    'cat_id' => '361',
    'cat_name' => '消毒除菌',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  156 => 
  array (
    'cat_id' => '387',
    'cat_name' => '干果坚果',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
  ),
  157 => 
  array (
    'cat_id' => '388',
    'cat_name' => '山珍山货',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '33',
  ),
);
?>